export const LOAD_PHILOS_START = 'LOAD_PHILOS_START';
export const LOAD_PHILOS_SUCCESS = 'LOAD_PHILOS_SUCCESS';
export const LOAD_PHILOS_FAIL = 'LOAD_PHILOS_FAIL';
export const ADD_PHILOS = 'ADD_PHILOS';